// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vvhbhrnapfmgebtiehxo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ2aGJocm5hcGZtZ2VidGllaHhvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc1NjY4NTYsImV4cCI6MjA3MzE0Mjg1Nn0.UKLAeCXs-uPnD1yxPiDXTN2Yy1ZbephBgyoZq9wjbAA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});